# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
auto_detect_solc = true
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000
# Configure remappings
remappings = [
  "@std=lib/forge-std/src/",
  "@solmate=lib/solmate/src/",
  "@openzepp=lib/openzeppelin-contracts/contracts/",
  "@v3-core=lib/v3-core/contracts/",
  "@v3-periphery=lib/v3-periphery/contracts/",
  "@uniswap/v3-core=lib/v3-core/",
  "@openzeppelin=lib/openzeppelin-contracts/",
]

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000